#
# Module manifest for module 'DemoToolkit'
#
# Generated by: Microsoft Corporation
#
# Generated on: 9/25/2012 (v1.3)   - Converted SnapIn into PS Module
# Modified on: 10/15/2012  (v1.3.1) - Replaced RootModule member by ModulestoProcess instead due to Win7 support

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'DemoToolkit.Cmdlets'

# Version number of this module.
ModuleVersion = '1.4.0'

# ID used to uniquely identify this module
GUID = '39E3EF29-C742-4AC8-A751-EDA978A2B34A'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all files packaged with this module
FileList =	'.\DemoToolkit.Cmdlets.dll-help.xml'	

# HelpInfo URI of this module
# HelpInfoURI = 'https://github.com/microsoft-dpe/demo-tools'

}